# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, help_text='300x300', max_length=255, null=True, upload_to='icon/userSignature/', verbose_name='Firma'),
        ),
    ]
