# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_authdiscountrouster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authdiscountrouster',
            name='signature',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='authdiscountrouster',
            name='signature_rep',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Firma Repesentante Legal'),
        ),
    ]
